### ISSUE TITLE
Stack crash

### ISSUE THREAD

**Issue by mhollis1980** [OliverLetterer/SLCoreDataStack#5]
I'm not sure why it's happening but what's happening is when I run my test application on Xcode 7 SLCoreDataStack gets stuck in an infinite loop but when I run it in Xcode 6 it finishes as expected. From what I can see there is a load method that is swizzling a couple of methods on ln 76. 
What I'm not sure about is it's actually swizzling on Xcode7 but not Xcode 6. Then on ln 82 of SLCoreDataStack seems to get into an infinite loop.

Is there something I have to do for it work properly on xcode7? 
Thanks,
Mike.

**Comment by OliverLetterer** [comment]
I'm not having any issues on my end and won't be able to reproduce the problem with this description.

**Comment by mhollis1980** [comment]
Fair enough. I was wondering if I could send you my test project? It's tiny only calling the fetch method. Is there a way to send zip files through github or is it okay if I send it to your actual email address?

Thanks for the help,
Mike.

**Comment by OliverLetterer** [comment]
I'm sorry Mike. I don't offer this kind of support for free open source projects right now. But since the source is publicly available, you should be able to debug your problem locally. A pull request is much appreciated but feel free to open another issue in case you find anything :)

**Comment by mhollis1980** [comment]
I thought I would update you on the issue I had and the solution to it in case other coders are having the same problem. 

When I was trying to crate SLCoreDataStack object in a test the follow line below would go into an infinite loop
```self = [self SL__CoreDataStackInitWithConcurrencyType:ct];``` 

I found in the Podfile in your Example and mine had one difference, use_frameworks!
I'm not sure why this actually made the issue go away but it did.

Thanks,
Mike.
